# Site settings
name: 赵杰的博客
email: w3313003@163.com
author: ZJ
url: http://w3313003.github.io
resume_site: http://w3313003.github.io/
github: https://github.com/w3313003/
baseurl: ""  #根目录
description: The cycle of life and death continues,i will live,they will die.
motto: 平凡之路。
#motto: 平凡之路。
banner: 且随疾风前行，身后亦须留心。
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: zhaojie
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : zhaojie
